//
//  annotation.m
//  Formation
//
//  Created by George Breen on 1/12/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//

#import "PdfAnnotation.h"
#import "PdfReader.h"


@implementation PdfAnnotation

-(id) initWithObjno:(int)objNo andGeneration:(int)genNo andDictionary:(PdfDictionary *)fd
{
	if((self = [super initWithObjno:objNo andGeneration:genNo andDictionary:fd])) 
		[fieldDictionary removeObjectForKey:APName];	// remove apperance element so it gets regenerated by the viewer
	return self;
}


-(void) drawWithContext:(CGContextRef)ctx andPageRect:(CGRect)pageRect andRotation:(CGPDFInteger) pageRotate		// will be overridden by subclasses
{
	
	CGAffineTransform trans = CGAffineTransformIdentity;
	trans = CGAffineTransformTranslate(trans, 0, pageRect.size.height);
	trans = CGAffineTransformScale(trans, 1.0, -1.0);
	
	CGRect rect = CGRectApplyAffineTransform(where, trans);
	
	rect.origin.y = (pageRect.size.height - rect.origin.y)-rect.size.height;
	
	// do whatever you need with the coordinates.
	// e.g. you could create a button and put it on top of your page
	// and use it to open the URL with UIApplication's openURL
	
	CGContextSetRGBFillColor(ctx, 1.0, 0.0,0.0, 0.5);
	CGContextFillRect(ctx, rect);
}


-(void) dealloc
{
//	Go through all of the annotations and release them.
//	then release the page.
	[super dealloc];
}
-(void) addToView: (UIView *)view withPageRect: (CGRect) pageRect
{
    
}

@end
